package com.jsq.enums;

/**
 * Created by cbc on 2017/11/17.
 */
public enum ValidateErrorType {
    UNKNOWN,
    ITEM_NAME_LENGTH,
    NULL_BUDGET_ITEM_CODE,
    ITEM_CODE_LENGTH,
    PERIOD_YEAR_FORMAT,
    PERIOD_QUARTER_FORMAT,
    ITEM_CODE_NOT_FOUND_OR_NAME_NOT_FOUND,
    PERIOD_NOT_EXIST,
    COMPANY_NOT_FOUND_OR_NAME_NOT_FOUND,
    DEPARTMENT_NOT_FOUND_OR_NAME_NOT_FOUND,
    NOT_FOUND_DIMENSION,
    NOT_FOUND_DIMENSION_VALUE_NAME,
    NOT_FOUND_DIMENSION_VALUE_CODE,
    NOT_FOUND_DIMENSION_VALUE,
    NULL_COMPANY,
    NULL_PERIOD,
    NULL_CURRENCY,
    NULL_AMOUNT,
    NULL_QUANTITY,
    NULL_SOURCE_TYPE,
    NULL_SOURCE_ITEM_CODE,
    NOT_FOUND_SOURCE_TYPE,
    NOT_FOUND_SOURCE_ITEM_CODE,
    NOT_UNQ_MAPPING_RELATIONSHIPS,
    NULL_ITEM_NAME,
    NULL_ITEM_TYPE_CODE,
    NOT_FOUND_ITEM_TYPE,
    NOT_UNQ_ITEM,
    NOT_FOUND_EMPLOYEE,
    NOT_FOUND_CURRENCY,
    NOT_FOUND_ITEM_ASSIGN_COMPANY,
    NOT_FOUND_JOURNAL_ASSIGN_ITEM






}
